language: cpp
sudo: false
dist: trusty
compiler:
  - gcc
os:
  - linux
install:
  - git submodule init
  - git submodule update
script:
  - |
    if [ $TRAVIS_OS_NAME == linux ]; then 
      mkdir -p build
      cd build
      cmake ../
      make
      ctest
    fi
after_success:
  echo "SUCCESS"
