language: cpp
sudo: false
dist: trusty
compiler:
  - gcc
os:
  - linux
git:
  - submodules: false
before_install:
  - git submodule update --init --remote --recursive
script:
  - if [ $TRAVIS_OS_NAME == linux ]; then mkdir build && cd build && cmake ../ && make && make test; fi

